$(function(){
    $(".hovermember").hover(function(){
      $(this).find(".memberpic").fadeIn();
    }
                    ,function(){
                        $(this).find(".memberpic").fadeOut();
                    }
                   );        
});